"""
Django settings for projects project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os



from dotenv import load_dotenv
import requests

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_SECRET_KEY = 'django-insecure-@qbn&@raick0x)i6d-zs)24_r5a)uoi8s#ukv@+e6!a^6624oh'
SECRET_KEY = os.getenv("SECRET_KEY", DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "0") == "1"

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "").split(",") if h.strip()]
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["localhost"]

CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "0") == "1"
CORS_ALLOWED_ORIGINS = [
    o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", "").split(",") if o.strip()
]

CORS_ALLOW_METHODS = ['DELETE','GET','OPTIONS','PATCH','POST','PUT']

# Application definition

INSTALLED_APPS = [
    
    'daphne',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    

    #add by sakhawat
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    'apps.users',
    'apps.subscription',
    #Add
    'apps.chats',
    'channels',
    'apps.smartcase',
    'apps.prisons',
    'apps.contact_support',
    'apps.cms',
    #
    'ckeditor',
     'ckeditor_uploader',
    "apps.resources",
    'django_filters',
    # 'apps.social_auth',

    # Google login
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'dj_rest_auth.registration',

    'apps.newsletter',

]


SITE_ID = 1


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'offline'},
        'EMAIL_AUTHENTICATION': True,
    }
}


REST_USE_JWT = True  

ACCOUNT_EMAIL_VERIFICATION = "optional"  
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
SOCIALACCOUNT_AUTO_SIGNUP = True




# Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
}



from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}




MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #google login
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'projects.urls'

AUTH_USER_MODEL = 'users.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'projects.wsgi.application'
ASGI_APPLICATION = 'projects.asgi.application'



REDIS_HOST = os.getenv("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

SQLITE_PATH = os.getenv("SQLITE_PATH")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': SQLITE_PATH or (BASE_DIR / "db.sqlite3"),
    }
}

CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Gmail SMTP server Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail SMTP server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or "no-reply@example.com"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_URL = '/static/'
WHITENOISE_IGNORE_MISSING_FILES = True
WHITENOISE_USE_FINDERS = True
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"




MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# CKEDITOR_UPLOAD_PATH = "uploads/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Stripe Settings
# STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
# STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
# STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")


STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

# STRIPE_WEBHOOK_SECRET = "whsec_b56d6e1125481467e5d7fbd3c7ac244e5342e2e22c195b2660564963e31ad4aa"
STRIPE_WEBHOOK_SECRET = "whsec_sAH6XJmUH8KlvYRdyCWW82oQ2y5eE1TD"  # Stripe webhook secret for testting

OPEN_AI_API_KEY = os.getenv("OPEN_AI_API_KEY")

CKEDITOR_UPLOAD_PATH = "uploads/"

CKEDITOR_ALLOW_NONIMAGE_FILES = True

CKEDITOR_CONFIGS = {
    'default': {
        'height': 500,
        'width': '100%',
        
        'toolbar': [
            ['Source', '-', 'Save', 'NewPage', 'Preview'],
            ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord'],
            ['Undo', 'Redo'],
            ['Find', 'Replace', '-', 'SelectAll'],
            ['Bold', 'Italic', 'Underline', 'Strike'],
            ['Subscript', 'Superscript'],
            ['NumberedList', 'BulletedList'],
            ['Outdent', 'Indent', 'Blockquote'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule', 'Smiley'],
            ['SpecialChar', 'PageBreak'],
            ['Styles', 'Format', 'Font', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks'],
        ],

        'extraPlugins': ','.join([
            'uploadimage',     # image upload
            'image2',
            'filebrowser',     # file upload
            'table',           # table support
            'clipboard',
            'dialog',
            'widget',
            'lineutils',
        ]),
    }
}
OPEN_AI_API_KEY = os.getenv("OPEN_AI_API_KEY")

# import datetime

# # JWT settings
# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=60),
#     'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=7),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
# }

# # Cookie settings (for your utils.py logic)
# SESSION_COOKIE_SECURE = False  # For local host False, for live server (HTTPS) True
# CSRF_COOKIE_SAMESITE = 'Lax'
# ACCESS_TOKEN_COOKIE_MAX_AGE = 3600  # 1 hour
# REFRESH_TOKEN_COOKIE_MAX_AGE = 604800  # 7 days








from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Division of Justice in America Admin",
    "SITE_HEADER": "D.O.J.A. Admin Panel",
    "DARK_MODE": True,

    "SIDEBAR": {
        "show_search": False,
        "command_search": False,
        "show_all_applications": False,

        "navigation": [

            # ===== Dashboard =====
            {
                "title": _("Dashboard"),
                "separator": True,
                "items": [
                    {
                        "title": _("Home"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            # ===== Users =====
            {
                "title": _("Users"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:users_user_changelist"),
                    },
                    {
                        "title": _("Profiles"),
                        "icon": "badge",
                        "link": reverse_lazy("admin:users_profile_changelist"),
                    },
                ],
            },

            # ===== Chats =====
            {
                "title": _("Chats"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Rooms"),
                        "icon": "forum",
                        "link": reverse_lazy("admin:chats_room_changelist"),
                    },
                    {
                        "title": _("Messages"),
                        "icon": "message",
                        "link": reverse_lazy("admin:chats_message_changelist"),
                    },
                    {
                        "title": _("User Status"),
                        "icon": "toggle_on",
                        "link": reverse_lazy("admin:chats_userstatus_changelist"),
                    },
                ],
            },

            # ===== Smart Case =====
            {
                "title": _("Smart Case"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Case Submissions"),
                        "icon": "gavel",
                        "link": reverse_lazy("admin:smartcase_casesubmission_changelist"),
                    },
                    {
                        "title": _("Case Documents"),
                        "icon": "description",
                        "link": reverse_lazy("admin:smartcase_casedocument_changelist"),
                    },
                    {
                        "title": _("Story"),
                        "icon": "description",
                        "link": reverse_lazy("admin:smartcase_story_changelist"),
                    },
                    {
                        "title": _("Podcast Stories"),
                        "icon": "description",
                        "link": reverse_lazy("admin:smartcase_podcaststory_changelist"),
                    },
                ],
            },

            # ===== Subscription =====
            {
                "title": _("Subscription"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Subscriptions"),
                        "icon": "payments",
                        "link": reverse_lazy("admin:subscription_subscription_changelist"),
                    },
                ],
            },

            # ===== Contact Support =====
            {
                "title": _("Support"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Contact Requests"),
                        "icon": "support_agent",
                        "link": reverse_lazy("admin:contact_support_contactus_changelist"),
                    },
                ],
            },

            # ===== CMS =====
            {
                "title": _("CMS"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Terms and Privacy"),
                        "icon": "policy",
                        "link": reverse_lazy("admin:cms_legaldocument_changelist"),
                    },
                    {
                        "title": _("FAQs"),
                        "icon": "help",
                        "link": reverse_lazy("admin:cms_faq_changelist"),
                    },
                ],
            },

            # ===== Resources =====
            {
                "title": _("Resources"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Legal Forms"),
                        "icon": "folder",
                        "link": reverse_lazy("admin:resources_legalform_changelist"),
                    },
                    {
                        "title": _("Prisons"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:resources_prison_changelist"),
                    },
                    {
                        "title": _("Legal Library"),
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:resources_legallibrary_changelist"),
                    },
                ],
            },

            # ===== Auth & Security =====
            {
                "title": _("Security"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Groups"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                    {
                        "title": _("Outstanding Tokens"),
                        "icon": "vpn_key",
                        "link": reverse_lazy("admin:token_blacklist_outstandingtoken_changelist"),
                    },
                    {
                        "title": _("Blacklisted Tokens"),
                        "icon": "block",
                        "link": reverse_lazy("admin:token_blacklist_blacklistedtoken_changelist"),
                    },
                ],
            },

            # ===== Django Core =====
            {
                "title": _("Django"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Sites"),
                        "icon": "language",
                        "link": reverse_lazy("admin:sites_site_changelist"),
                    },
                    {
                        "title": _("Email Addresses"),
                        "icon": "email",
                        "link": reverse_lazy("admin:account_emailaddress_changelist"),
                    },
                    {
                        "title": _("Social Apps"),
                        "icon": "apps",
                        "link": reverse_lazy("admin:socialaccount_socialapp_changelist"),
                    },
                    {
                        "title": _("Social Tokens"),
                        "icon": "token",
                        "link": reverse_lazy("admin:socialaccount_socialtoken_changelist"),
                    },
                    {
                        "title": _("Social Accounts"),
                        "icon": "account_circle",
                        "link": reverse_lazy("admin:socialaccount_socialaccount_changelist"),
                    },
                    {
                        "title": _("Auth Tokens"),
                        "icon": "key",
                        "link": reverse_lazy("admin:authtoken_tokenproxy_changelist"),
                    },
                ],
            },
        ],
    },
}

import cloudinary

cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME'),
    api_key=os.getenv('CLOUDINARY_API_KEY'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET'),
    secure=True
)