# Generated by Django 5.2.4 on 2026-03-16 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_title', models.CharField(max_length=255)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('press_release', models.TextField()),
                ('press_release_enhanced', models.TextField(blank=True, help_text='Polished version by AI', null=True)),
                ('state', models.CharField(max_length=100)),
                ('federal_district', models.CharField(blank=True, max_length=255, null=True)),
                ('court_type', models.CharField(blank=True, max_length=100, null=True)),
                ('external_link', models.URLField(blank=True, help_text='User pastes doc link here', max_length=500, null=True)),
                ('ai_analysis_summary', models.TextField(blank=True, help_text='Summary generated from the link/file', null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cases/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='smartcase.casesubmission')),
            ],
        ),
    ]
