# Generated by Django 5.2.4 on 2026-03-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesubmission',
            name='press_release',
            field=models.TextField(blank=True, null=True),
        ),
    ]
