# Generated by Django 5.2.4 on 2026-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0003_casesubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
