# Generated by Django 5.2.4 on 2026-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0004_casedocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubmission',
            name='case_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
