# Generated by Django 5.2.4 on 2026-04-06 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0005_casesubmission_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubmission',
            name='key_legal_arguments',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Key legal arguments extracted by AI', null=True),
        ),
    ]
