# Generated by Django 5.2.4 on 2026-04-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0006_casesubmission_key_legal_arguments'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubmission',
            name='accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the case was accepted', null=True),
        ),
    ]
