# Generated by Django 5.2.4 on 2026-04-12 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0007_casesubmission_accepted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubmission',
            name='key_legal_arguments',
        ),
        migrations.CreateModel(
            name='LegalArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_arguments', to='smartcase.casesubmission')),
            ],
        ),
    ]
