# Generated by Django 5.2.4 on 2026-04-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0008_remove_casesubmission_key_legal_arguments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='document_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
