# Generated by Django 5.2.4 on 2026-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0010_story_storyfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('files', models.FileField(upload_to='podcast_stories/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Podcast Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
