# Generated by Django 5.2.4 on 2026-05-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0011_podcaststory'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyfile',
            name='story_file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
