# Generated by Django 5.2.4 on 2026-05-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartcase', '0012_storyfile_story_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcaststory',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
