# Generated by Django 5.2.4 on 2026-03-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalform',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formfile',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='legal/pdfs/'),
        ),
    ]
