# Generated by Django 5.2.4 on 2026-04-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_legalform_short_description_alter_formfile_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('name_title', models.CharField(blank=True, max_length=255, null=True)),
                ('name_display', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('security_level', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('facl_type_description', models.CharField(blank=True, max_length=255, null=True)),
                ('has_camp', models.BooleanField(default=False)),
                ('has_fsl', models.BooleanField(default=False)),
                ('has_fdc', models.BooleanField(default=False)),
                ('has_sff', models.BooleanField(default=False)),
                ('has_ihp', models.BooleanField(default=False)),
                ('image_normal', models.CharField(blank=True, max_length=255, null=True)),
                ('image_small', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
