# Generated by Django 5.2.4 on 2026-04-08 08:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_prison'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('full_text', ckeditor.fields.RichTextField()),
                ('uploade_file', models.FileField(blank=True, null=True, upload_to='legal/library_files/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
