# Generated by Django 5.2.4 on 2026-04-30 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_legallibrary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='resources.prison')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('staff', 'Staff'), ('library', 'Library'), ('food', 'Food Services'), ('freedom', 'Freedom / Left Alone'), ('safety', 'Safety'), ('equipment', 'Recreational Equipment'), ('unicor', 'Unicor'), ('commissary', 'Commissary'), ('wait', 'program wait time'), ('cleanliness', 'Cleanliness'), ('visitation', 'Visitation'), ('programs', 'Inmate Self Programs'), ('time', 'Overall Place to Do Time')], max_length=50)),
                ('score', models.FloatField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='resources.review')),
            ],
        ),
    ]
