# Generated by Django 5.2.4 on 2026-05-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_review_categoryrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrating',
            name='category',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('library', 'Library'), ('food', 'Food Services'), ('freedom', 'Freedom / Left Alone'), ('safety', 'Safety'), ('equipment', 'Recreational Equipment'), ('unicor', 'Unicor'), ('commissary', 'Commissary'), ('wait', 'program wait time'), ('cleanliness', 'Cleanliness'), ('visitation', 'Visitation'), ('programs', 'Inmate Self Programs'), ('time', 'Overall Place to Do Time')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoryrating',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_ratings', to='resources.review'),
        ),
        migrations.AlterField(
            model_name='categoryrating',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
