# Generated by Django 5.2.4 on 2026-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_alter_categoryrating_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="review_file",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
