# Generated by Django 5.2.4 on 2026-06-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_review_review_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prison",
            name="code",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
