# Generated by Django 5.2.4 on 2026-03-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatus',
            old_name='is_online',
            new_name='auto_status',
        ),
        migrations.AddField(
            model_name='userstatus',
            name='manual_status',
            field=models.BooleanField(default=True),
        ),
    ]
