# Generated by Django 5.2.4 on 2026-03-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_podcast_story',
            field=models.BooleanField(default=False, help_text='Featured in Podcast/Story for Star badge'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_letters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_posts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
