# Generated by Django 5.2.4 on 2026-03-28 08:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_conditions', 'Terms and Conditions')], max_length=50, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('version', models.CharField(default='1.0.0', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
