# Generated by Django 5.2.4 on 2026-03-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text=' Serial Number (e.g., 1, 2, 3)'),
        ),
    ]
