# Generated by Django 5.2.4 on 2026-06-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Promo Active"),
                ),
                (
                    "max_limit",
                    models.IntegerField(default=1000, verbose_name="Promo Limit"),
                ),
            ],
            options={
                "verbose_name": "Promo Configuration",
                "verbose_name_plural": "Promo Configurations",
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
